abstract test sequencer run & raise error when accessing identifier before eval
flojoy-ai/studio pull request #1083
Opened 2024-02-14 20:57 UTC by izi-on

2024-02-15 16:34 UTC, LatentDream requested changes
lgtm, just some small things.
Also not sure we need a __init__ in each directory ?

2024-02-15 16:34 UTC, LatentDream commented on captain/parser/bool_parser/expressions/exceptions.py
> +        self.message = f"Cannot access identifier {message} before evaluation"
The error is good, but a little bit too "comp sci" for a user. Maybe something like:
```
f"Unable to access test result for {message} as it's executed afterward"
```

2024-02-15 16:34 UTC, LatentDream commented on captain/utils/test_sequencer/run_test_sequence.py
> +    children_getter, test_result = await cur(node)  # sus name for the variable
Ahahha, would remove the comment tho

2024-02-16 00:06 UTC, itsjoeoui approved these changes
lgtm

2024-02-16 00:06 UTC, merged