Added opening and closing node modals
flojoy-ai/studio pull request #527
Opened 2023-06-08 19:02 UTC by Lans1975

2023-06-08 19:04 UTC, yassine-moumen commented
## To access Flojoy-studio build from this pull request, you can use the following URLs: 

http://44.204.181.68:3000 
http://527.flojoy-test.com:3000 
Please note that it may take a few minutes for the instance to start up, so please be patient. 

It is important to know that the instance will automatically shut down after one hour to conserve resources. If you wish to start the instance again after it shuts down, you can use this API : 
https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0d606d28f03efaf0f

2023-06-08 22:14 UTC, jackparmer approved these changes

2023-06-22 18:53 UTC, smahmed776 requested changes

2023-06-22 18:53 UTC, smahmed776 commented on cypress/e2e/04_opening_and_closing_node_modals.cy.ts
> +    cy.xpath("//div[contains(text(), 'LINSPACE')]").click();
Instead of checking for only two nodes explicitly, can we have an array of nodes and loop through each node and do the same action for them all?

2023-06-22 19:07 UTC, smahmed776 commented
Also, some cypress tests are failing in the CI workflow could you please make sure that all tests are passed?

2023-07-31 17:53 UTC, smahmed776 commented
This PR looks unmaintained and cypress tests are updated with Percy now. closing as redundant...

2023-07-31 17:53 UTC, closed without merging