Dynamic param
flojoy-ai/studio pull request #795
Opened 2023-08-14 20:14 UTC by Orisu179

2023-08-21 17:09 UTC, JeffDotPng requested changes

2023-08-23 07:18 UTC, Orisu179 commented on PYTHON/manifest/build_ast.py
> +    default_value = ast.literal_eval(node.args.defaults[0])
For now yes. Extending parsing shouldn't be too hard, the hard part would be how to filter afterwards.

2023-08-25 12:42 UTC, trbritt commented
Hi Tyler,

This looks good to me with the above changes!

2023-09-04 15:39 UTC, itsjoeoui approved these changes
merged for now

2023-09-04 15:41 UTC, merged