Electron updater is working
flojoy-ai/studio pull request #870
Opened 2023-09-11 21:17 UTC by smahmed776

2023-09-13 23:05 UTC, itsjoeoui requested changes

2023-09-13 23:05 UTC, itsjoeoui commented on electron/main/update.ts
> +const CHECK_FOR_UPDATE_INTERVAL = 60000; // 1 mins default
```suggestion
const CHECK_FOR_UPDATE_INTERVAL = 600000; // 10 mins default
```

2023-09-14 00:21 UTC, JeffDotPng requested changes

2023-09-14 00:21 UTC, JeffDotPng commented on electron/main/index.ts
> +  });
you can get rid of this, i deleted it when i fixed saving apps

2023-09-14 00:21 UTC, JeffDotPng commented on electron/main/index.ts
> +import { writeFileSync } from "fs";
```suggestion
import fs from "fs";
```
`handleWriteFileSync` has an error otherwise

2023-09-14 00:21 UTC, JeffDotPng commented on electron/main/update.ts
> +  });
```suggestion
  autoUpdater.on("checking-for-update", () => logger.log("checking for update...."));
```

2023-09-14 00:21 UTC, JeffDotPng commented on electron/main/update.ts
> +        } is found! Current version is ${app.getVersion()}`,
```suggestion
        detail: `An update to v${
          arg.version
        } is available! Current version is ${app.getVersion()}`,
```

2023-09-14 00:45 UTC, JeffDotPng approved these changes

2023-09-14 18:00 UTC, merged